name: CI/CD
on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened, edited, closed, labeled, unlabeled ]
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run make test
        run: make test